#!/bin/bash
# Option for PBS
### Job name
#PBS -N trimming_step

### Join queuing system output and error files into a single output file
#PBS -j oe

### Request nodes, memory, walltime. N.B. THESE ARE REQUIRED
#PBS -l select=1:ncpus=12:mem=40g

### Set a list of email addresses that receive mail from PBS
#PBS -M saveria.mazzara@gmail.com

### Specify in which case an email should be send, a=abort, b=begin, e=end
#PBS -m abe

### Account string: defines the account string associated with the job
#PBS -A mazzara

# This script performs the trimming step



## Configuration 
## --------------------

# Activate the conda environment
source activate /home/mazzara/.conda/envs/rnaseq_env

# path to the run folder
INPUT_DIR="/data/RNAseq/BCL2"
OUTPUT_DIR="/scratch/trimming_mapping/BCL2/"


## Trimming Step
## --------------------


#SAMPLE=`basename $OUTPREFIX`
#cd $INPUT_DIR/$SAMPLE

# example related to one sample of the RNA cohort
bbduk.sh in=$INPUT_DIR/Sample1/Sample1_L001_R1_001.fastq.gz in2=$INPUT_DIR/Sample1/Sample1_L001_R2_001.fastq.gz out=$OUTPUT_DIR/Sample1/Sample1_trim_R1.fastq.gz out2=$OUTPUT_DIR/Sample1/Sample1_trim_R2.fastq.gz qtrim=r minlen=25

# Deactivate the environment
source deactivate /home/mazzara/.conda/envs/rnaseq_env
