#!/bin/bash
# Option for PBS
### Job name
#PBS -N quality_check_post_trimming_step

### Join queuing system output and error files into a single output file
#PBS -j oe

### Request nodes, memory, walltime. N.B. THESE ARE REQUIRED
#PBS -l select=1:ncpus=12:mem=40g

### Set a list of email addresses that receive mail from PBS
#PBS -M saveria.mazzara@gmail.com

### Specify in which case an email should be send, a=abort, b=begin, e=end
#PBS -m abe

### Account string: defines the account sring associated with the job
#PBS -A mazzara

# This script performs quality check after post trimming

## Configuration
## ----------------

# Activate the conda environment
source activate /home/mazzara/.conda/envs/rnaseq_env

# path to the run folder
RUN_PATH="/data/RNAseq/BCL2"
OUTPUT_PATH="/data/RNAseq/BCL2/"

## Quality Check Post Trimming
## ---------------------------

for file in $(ls $RUN_PATH | grep "Sample")
do
  SAMPLE=`basename $file`
  cd $RUN_PATH/$SAMPLE
  fastqc --o $OUTPUT_PATH/$SAMPLE ${SAMPLE}_R1_trim.fastq.gz ${SAMPLE}_R2_trim.fastq.gz
done

# Deactivate the environment 
source deactivate /home/mazzara/.conda/envs/rnaseq_env

