#!/bin/bash
# Option for PBS
### Job name
#PBS -N genome_indexes_step

### Join queuing system output and error files into a single output file
#PBS -j oe

### Request nodes, memory, walltime. N.B. THESE ARE REQUIRED
#PBS -l select=1:ncpus=12:mem=40g

### Set a list of email addresses that receive mail from PBS
#PBS -M saveria.mazzara@gmail.com

### Specify in which case an email should be send, a=abort, b=begin, e=end
#PBS -m abe

### Account string: defines the account string associated with the job
#PBS -A mazzara

# This script performs the creation of a STAR genome index file



## Configuration 
## --------------------

# Activate the conda environment
source activate /home/mazzara/.conda/envs/rnaseq_env

# path to the run folder
GENOME_DIR="/scratch/genome/"


## Generate genome indexes Step
## --------------------

cd $GENOME_DIR

#mkdir $GENOME_DIR/STAR

STAR --runThreadN 8 --runMode genomeGenerate --genomeDir /scratch/genome/STAR --genomeFastaFiles /scratch/genome/GRCh38.primary_assembly.genome.fa --sjdbGTFfile /scratch/genome/gencode.v34.primary_assembly.annotation.gtf --sjdbOverhang 50 

# Deactivate the environment
source deactivate /home/mazzara/.conda/envs/rnaseq_env
